My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('app_login.urls')),
    path('blog/',include('app_blog.urls')),
    path('',views.index,name="index" ),
]

app_blog/urls.py
from django.urls import path
from app_blog import views


app_name='app_blog'

urlpatterns = [
    path('',views.BlogList.as_view(),name="blogList" ),
    path('write/',views.CreateBlog.as_view(),name="create_blog" ),
    path('details/<int:id>',views.blog_details,name="blog_details" ),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    ]

app_login/urls.py
from django.urls import path
from app_login import views



app_name='app_login'
urlpatterns = [
    path('signup/',views.sign_up,name="signup" ),
    path('signin/',views.login_page,name="signin" ),
    path('logout/',views.logout_page,name="logout" ),
    path('profile/',views.profile,name="profile" ),
    path('change_profile/',views.user_change,name="user_change" ),
    path('password/', views.pass_change, name='pass_change'),

    ]

app_blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class blog(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='post_author')
    blog_title=models.CharField(max_length=264, verbose_name='put a title')
    slug=models.SlugField(max_length=264,unique=True)
    blog_content=models.TextField(verbose_name="What's your name")
    blog_image=models.ImageField(upload_to='blog_images',verbose_name="Image")
    publish_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.blog_title


class comment(models.Model):
        blogc=models.ForeignKey(blog,on_delete=models.CASCADE,related_name='blog_comment')
        user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
        comments=models.TextField()
        comment_date=models.DateTimeField(auto_now_add=True)

        def __str__(self):
            return self.comments


class likes(models.Model):
    blogc=models.ForeignKey(blog,on_delete=models.CASCADE,related_name='blog_like')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_like')
    def __str__(self):
        return self.user + " likes " + self.blog

app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class userProfile(models.Model):
    user=models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profile_pic')

app_blog/forms.py
from django import forms
from app_blog.models import blog, comment
class CommentForm(forms.ModelForm):
    class Meta:
        model=comment
        fields=('comments',)

app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email=forms.EmailField(required=True)
    class Meta:
        model=User
        fields=('username','email','password1','password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model=User
        fields=('username','email','first_name','last_name','password')

My_Blog_Project/views.py
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse

def index(request):
    return HttpResponseRedirect(reverse('app_blog:blogList'))

app_blog/views.py
from django.shortcuts import render , HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView
from app_blog.models import blog, comment, likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from app_blog.forms import CommentForm
import uuid
# Create your views here.




class CreateBlog(LoginRequiredMixin, CreateView):
    model = blog
    template_name = 'app_blog/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image',)
    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))


class BlogList(ListView):
    context_object_name = 'blogs'
    model = blog
    template_name = 'app_blog/blogList.html'
    queryset=blog.objects.order_by('-publish_date')



@login_required
def blog_details(request,id):
    ablog=blog.objects.get(pk=id)
    comment_form=CommentForm()
    already_liked = likes.objects.filter(blogc=ablog, user= request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method=='POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            com=comment_form.save(commit=False)
            com.user=request.user
            com.blogc=ablog
            com.save()
            return HttpResponseRedirect(reverse('app_blog:blog_details',kwargs={'id':id}))
    return render(request,'app_blog/blog_details.html',context={'blog':ablog, 'comment_form':comment_form, 'liked':liked})


@login_required
def liked(request, pk):
    ablog = blog.objects.get(pk=pk)
    user = request.user
    already_liked = likes.objects.filter(blogc=ablog, user=user)
    if not already_liked:
        liked_post = likes(blogc=ablog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'id':ablog.id}))



@login_required
def unliked(request, pk):
    ablog = blog.objects.get(pk=pk)
    user = request.user
    already_liked = likes.objects.filter(blogc=ablog, user=user)
    already_liked.delete()

    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'id':ablog.id}))

app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login,authenticate,logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from app_login.forms import SignUpForm,UserProfileChange
# Create your views here.

def sign_up(request):
    form=SignUpForm()
    registered=False
    if request.method=='POST':
        form=SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered=True

    diction={'form':form, 'registered':registered}
    return render(request,'app_login/signup.html',context=diction)

def login_page(request):
    form=AuthenticationForm()
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get('username')
            passw=form.cleaned_data.get('password')
            user=authenticate(username=uname,password=passw)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

    return render(request,'app_login/login.html',context={'form':form})


@login_required
def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    return render(request,'app_login/profile.html', context={})


@login_required
def user_change(request):
    current_user=request.user
    form=UserProfileChange(instance=current_user)
    if request.method =='POST':
        form=UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form=UserProfileChange(instance=current_user)

    return render(request,'app_login/change_profile.html', context={'form':form})



@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'app_login/pass_change.html', context={'form':form, 'changed':changed})

templates/app_blog/blogList.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %}
Home
{% endblock %}
{% block body_block %}
{% for blog in blogs %}
<h3>{{blog.blog_title}}</h3>
<h4>{{blog.publish_date}}</h4>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_images}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'app_blog:blog_details' id=blog.id %}">Read More</a></p>
    <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
  </div>
</div>
<hr>
{% endfor %}
{% endblock %}

templates/app_blog/blog_details.html
{% extends 'base.html' %}
{% block title_block %}
{{blog.blog_title}}
{% endblock %}
{% block body_block %}
<div class="row">
  <div class="col-sm-6">
    <h2>{{blog.blog_title}}</h2>
    <h4>Posted by:@{{blog.author}}</h4>
    <i><h6>Published on:{{blog.publish_date}}</h6></i>
    <i><h6>Updated on:{{blog.update_date}}</h6></i>
    <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
  </div>

  <div class="col-sm-6">
    {{blog.blog_content}}
    <hr>
    {% if not liked %}
    <a href="{% url 'app_blog:liked_post' pk=blog.pk %}">
      <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
    </a>
    {% else %}
    <a href="{% url 'app_blog:unliked_post' pk=blog.pk %}">
      <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
    </a>
    {% endif %}
  </div>

</div>
<div class="row">
  <div class="col-sm-6">
    <h5>Comments:</h5>
    {% for comment in blog.blog_comment.all %}
    <p><a href="#">@{{comment.user}}</a> {{comment.comments}}
    <i><h6>{{comment.comment_date}}</h6></i>
    </p>
    {% endfor %}
  </div>
  <div class="col-sm-6">
    <form  method="POST">

    {{comment_form}}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">comment</button>
    </form>
  </div>
</div>


{% endblock %}

templates/app_blog/create_blog.html
{% extends 'base.html' %}
{% block title_block %}
Home
{% endblock %}
{% block body_block %}
<h2>Write your blog</h2>
<form method="POST" enctype="multipart/form-data">
  {{form.as_p}}
  {% csrf_token %}
  <button type="submit" name="button" class="btn btn-success btn-sm">publish</button>
</form>
{% endblock %}

templates/app_blog/edit_blog.html
{% extends 'base.html' %}
{% block title_block %}
Home
{% endblock %}
{% block body_block %}
{% endblock %}

templates/app_blog/my_blog.html
{% extends 'base.html' %}
{% block title_block %}
Home
{% endblock %}
{% block body_block %}
{% endblock %}

templates/app_login/change_profile.html
{% extends 'base.html' %}

{% block title_block %}
Change Profile
{% endblock %}
{% block body_block %}
<form  method="POST">
  {{ form.as_p}}
  {% csrf_token %}
  <button type="submit" name="button" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

templates/app_login/login.html
{% extends 'base.html' %}

{% block title_block %}
Sign up
{% endblock %}
{% block body_block %}
<h2>Login</h2>
<form  method="POST">
  {{form.as_p}}
  {% csrf_token %}
  <button type="submit" name="button" class="btn btn-primary btn-sm">Login</button>
</form>
{% endblock %}

templates/app_login/pass_change.html
{% extends 'base.html' %}

{% block title_block %} Change Pass {% endblock %}
{% block body_block %}
{% if changed %}
<div class="alert alert-success">
  Password Change Successfully!
</div>
{% endif %}
<form method="POST">
  {{ form.as_p }}
  {% csrf_token %}
  <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

templates/app_login/profile.html
{% extends 'base.html' %}

{% block title_block %}
Profile
{% endblock %}
{% block body_block %}
<h2>Your profile</h2>
<p>Username:{{user.username}}</p>
<p>Email:{{user.email}}</p>
<p>Name:{{user.first_name}} {{user.last_name}}</p>
<br>
<a href="{% url 'app_login:user_change' %}" class="btn btn-warning">Change profile info</a>
{% endblock %}

templates/app_login/signup.html
{% extends 'base.html' %}

{% block title_block %}
Sign up
{% endblock %}
{% block body_block %}
{%if registered%}
<div class="alert alert-success">
  Successfully Registered
  <a href="{% url 'app_login:signin'%}">Login here</a>
</div>
{% else %}
<form method="POST">
  {{form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="submit">
</form>
<p>Already have an account...<a href=""{% url 'app_login:signin'%}"">Login here</a></p>
{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title_block %}
    Blogs
    {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_login:logout' %}">logout </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_login:profile' %}">Your Profile </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_blog:create_blog' %}">Write blog </a>
      </li>
      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_login:signup' %}">Sign up </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_login:signin' %}">Sign in </a>
      </li>
      {% endif %}

    </ul>
  </div>
</nav>

{% block body_block %}

{% endblock %}

  </body>
</html>